export type FeedCatalogEntry = {
  publisher: string;
  journal: string;
  url: string;
  subjects: string[];
};

export const feedCatalog: FeedCatalogEntry[] = [
  {
    publisher: "Nature",
    journal: "Nature",
    url: "https://www.nature.com/nature.rss",
    subjects: ["multidisciplinary", "science"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Health Economics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=health_economics",
    subjects: ["health economics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Health Informatics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=health_informatics",
    subjects: ["health informatics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Health Policy",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=health_policy",
    subjects: ["health policy", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Health Systems and Quality Improvement",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=health_systems_and_quality_improvement",
    subjects: ["health systems", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Hematology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=hematology",
    subjects: ["hematology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: HIV/AIDS",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=hiv_aids",
    subjects: ["hiv", "infectious disease"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Infectious Diseases",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=infectious_diseases",
    subjects: ["infectious disease", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Intensive Care and Critical Care Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=intensive_care_and_critical_care_medicine",
    subjects: ["critical care", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Medical Education",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=medical_education",
    subjects: ["medical education", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Medical Ethics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=medical_ethics",
    subjects: ["medical ethics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Nephrology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=nephrology",
    subjects: ["nephrology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Neurology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=neurology",
    subjects: ["neurology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Nursing",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=nursing",
    subjects: ["nursing", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Nutrition",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=nutrition",
    subjects: ["nutrition", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Obstetrics and Gynecology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=obstetrics_and_gynecology",
    subjects: ["obstetrics", "gynecology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Occupational and Environmental Health",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=occupational_and_environmental_health",
    subjects: ["occupational health", "environment"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Oncology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=oncology",
    subjects: ["oncology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Ophthalmology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=ophthalmology",
    subjects: ["ophthalmology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Orthopedics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=orthopedics",
    subjects: ["orthopedics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Otolaryngology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=otolaryngology",
    subjects: ["otolaryngology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Pain Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=pain_medicine",
    subjects: ["pain medicine", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Palliative Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=palliative_medicine",
    subjects: ["palliative care", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Pathology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=pathology",
    subjects: ["pathology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Pediatrics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=pediatrics",
    subjects: ["pediatrics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Pharmacology and Therapeutics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=pharmacology_and_therapeutics",
    subjects: ["pharmacology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Primary Care Research",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=primary_care_research",
    subjects: ["primary care", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Psychiatry and Clinical Psychology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=psychiatry_and_clinical_psychology",
    subjects: ["psychiatry", "psychology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Public and Global Health",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=public_and_global_health",
    subjects: ["public health", "global health"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Radiology and Imaging",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=radiology_and_imaging",
    subjects: ["radiology", "imaging"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Geriatrics",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=geriatrics",
    subjects: ["geriatrics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Rehabilitation Medicine and Physical Therapy",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=rehabilitation_medicine_and_physical_therapy",
    subjects: ["rehabilitation", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Genetic and Genomic Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=genetic_and_genomic_medicine",
    subjects: ["genomics", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Epidemiology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=epidemiology",
    subjects: ["epidemiology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Cancer Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=cancer_biology",
    subjects: ["cancer", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Cell Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=cell_biology",
    subjects: ["cell biology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Developmental Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=developmental_biology",
    subjects: ["developmental biology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Ecology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=ecology",
    subjects: ["ecology", "environment"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Evolutionary Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=evolutionary_biology",
    subjects: ["evolution", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Genetics",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=genetics",
    subjects: ["genetics", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Genomics",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=genomics",
    subjects: ["genomics", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Immunology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=immunology",
    subjects: ["immunology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Microbiology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=microbiology",
    subjects: ["microbiology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Molecular Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=molecular_biology",
    subjects: ["molecular biology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Neuroscience",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=neuroscience",
    subjects: ["neuroscience", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Paleontology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=paleontology",
    subjects: ["paleontology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Pathology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=pathology",
    subjects: ["pathology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Pharmacology and Toxicology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=pharmacology_and_toxicology",
    subjects: ["pharmacology", "toxicology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Physiology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=physiology",
    subjects: ["physiology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Plant Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=plant_biology",
    subjects: ["plant science", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Scientific Communication and Education",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=scientific_communication_and_education",
    subjects: ["scientific communication", "education"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Synthetic Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=synthetic_biology",
    subjects: ["synthetic biology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Systems Biology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=systems_biology",
    subjects: ["systems biology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Zoology",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=zoology",
    subjects: ["zoology", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: All",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=all",
    subjects: ["preprints", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Addiction Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=addiction_medicine",
    subjects: ["addiction medicine", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Allergy and Immunology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=allergy_and_immunology",
    subjects: ["allergy", "immunology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Anesthesia",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=anesthesia",
    subjects: ["anesthesia", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Cardiovascular Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=cardiovascular_medicine",
    subjects: ["cardiology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Dentistry and Oral Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=dentistry_and_oral_medicine",
    subjects: ["dentistry", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Dermatology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=dermatology",
    subjects: ["dermatology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Emergency Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=emergency_medicine",
    subjects: ["emergency medicine", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Endocrinology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=endocrinology",
    subjects: ["endocrinology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Gastroenterology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=gastroenterology",
    subjects: ["gastroenterology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Respiratory Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=respiratory_medicine",
    subjects: ["respiratory medicine", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Rheumatology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=rheumatology",
    subjects: ["rheumatology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Sexual and Reproductive Health",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=sexual_and_reproductive_health",
    subjects: ["reproductive health", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "Annals of the Rheumatic Diseases",
    url: "https://ard.bmj.com/rss/current.xml",
    subjects: ["rheumatology", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "Journal of Medical Genetics",
    url: "https://jmg.bmj.com/rss/current.xml",
    subjects: ["genetics", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "Journal of Neurology, Neurosurgery & Psychiatry",
    url: "https://jnnp.bmj.com/rss/current.xml",
    subjects: ["neurology", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "Thorax",
    url: "https://thorax.bmj.com/rss/current.xml",
    subjects: ["respiratory medicine", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "British Journal of Sports Medicine",
    url: "https://bjsm.bmj.com/rss/current.xml",
    subjects: ["sports medicine", "medicine"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "IEEE Transactions on Pattern Analysis and Machine Intelligence",
    url: "https://ieeexplore.ieee.org/rss/TOC34.XML",
    subjects: ["computer science", "artificial intelligence"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "IEEE Transactions on Medical Imaging",
    url: "https://ieeexplore.ieee.org/rss/TOC42.XML",
    subjects: ["medical imaging", "engineering"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "IEEE Transactions on Robotics",
    url: "https://ieeexplore.ieee.org/rss/TOC8860.XML",
    subjects: ["robotics", "engineering"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "IEEE/ACM Transactions on Computational Biology and Bioinformatics",
    url: "https://ieeexplore.ieee.org/rss/TOC8857.XML",
    subjects: ["bioinformatics", "computer science"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "ACM Computing Surveys",
    url: "https://dl.acm.org/action/showFeed?type=etoc&feed=rss&jc=csur",
    subjects: ["computer science", "reviews"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "Journal of the ACM",
    url: "https://dl.acm.org/action/showFeed?type=etoc&feed=rss&jc=jacm",
    subjects: ["computer science"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "ACM Transactions on Graphics",
    url: "https://dl.acm.org/action/showFeed?type=etoc&feed=rss&jc=tog",
    subjects: ["computer graphics", "computer science"],
  },
  {
    publisher: "IEEE/ACM",
    journal: "ACM Transactions on Intelligent Systems and Technology",
    url: "https://dl.acm.org/action/showFeed?type=etoc&feed=rss&jc=tist",
    subjects: ["artificial intelligence", "computer science"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Cancer",
    url: "https://www.nature.com/nrc.rss",
    subjects: ["medicine", "oncology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Cardiology",
    url: "https://www.nature.com/nrcardio.rss",
    subjects: ["medicine", "cardiology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Chemistry",
    url: "https://www.nature.com/natrevchem.rss",
    subjects: ["chemistry", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Clinical Oncology",
    url: "https://www.nature.com/nrclinonc.rss",
    subjects: ["medicine", "oncology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Disease Primers",
    url: "https://www.nature.com/nrdp.rss",
    subjects: ["medicine", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Drug Discovery",
    url: "https://www.nature.com/nrd.rss",
    subjects: ["medicine", "pharmacology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Earth & Environment",
    url: "https://www.nature.com/natrevearthenviron.rss",
    subjects: ["earth science", "environment", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Endocrinology",
    url: "https://www.nature.com/nrendo.rss",
    subjects: ["medicine", "endocrinology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Gastroenterology & Hepatology",
    url: "https://www.nature.com/nrgastro.rss",
    subjects: ["medicine", "gastroenterology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Genetics",
    url: "https://www.nature.com/nrg.rss",
    subjects: ["biology", "genetics", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Immunology",
    url: "https://www.nature.com/nri.rss",
    subjects: ["biology", "immunology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Microbiology",
    url: "https://www.nature.com/nrmicro.rss",
    subjects: ["biology", "microbiology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Molecular Cell Biology",
    url: "https://www.nature.com/nrm.rss",
    subjects: ["biology", "cell biology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Nephrology",
    url: "https://www.nature.com/nrneph.rss",
    subjects: ["medicine", "nephrology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Neurology",
    url: "https://www.nature.com/nrneurol.rss",
    subjects: ["medicine", "neurology", "review"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Neuroscience",
    url: "https://www.nature.com/nrn.rss",
    subjects: ["biology", "neuroscience", "review"],
  },
  {
    publisher: "BMJ",
    journal: "Heart",
    url: "https://heart.bmj.com/rss/current.xml",
    subjects: ["cardiology", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "Gut",
    url: "https://gut.bmj.com/rss/current.xml",
    subjects: ["gastroenterology", "medicine"],
  },
  {
    publisher: "BMJ",
    journal: "The BMJ",
    url: "http://feeds.bmj.com/bmj/recent",
    subjects: ["medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Sports Medicine",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=sports_medicine",
    subjects: ["sports medicine", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Surgery",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=surgery",
    subjects: ["surgery", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Toxicology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=toxicology",
    subjects: ["toxicology", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Transplantation",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=transplantation",
    subjects: ["transplantation", "medicine"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "medRxiv: Urology",
    url: "https://connect.medrxiv.org/medrxiv_xml.php?subject=urology",
    subjects: ["urology", "medicine"],
  },
  {
    publisher: "Nature",
    journal: "Communications Biology",
    url: "https://www.nature.com/commsbio.rss",
    subjects: ["biology", "open access"],
  },
  {
    publisher: "Nature",
    journal: "Communications Chemistry",
    url: "https://www.nature.com/commschem.rss",
    subjects: ["chemistry", "open access"],
  },
  {
    publisher: "Nature",
    journal: "Communications Earth & Environment",
    url: "https://www.nature.com/commsenv.rss",
    subjects: ["earth science", "environment"],
  },
  {
    publisher: "Nature",
    journal: "Communications Engineering",
    url: "https://www.nature.com/commseng.rss",
    subjects: ["engineering", "open access"],
  },
  {
    publisher: "Nature",
    journal: "Communications Materials",
    url: "https://www.nature.com/commsmat.rss",
    subjects: ["materials", "open access"],
  },
  {
    publisher: "Nature",
    journal: "Communications Medicine",
    url: "https://www.nature.com/commsmed.rss",
    subjects: ["medicine", "open access"],
  },
  {
    publisher: "Nature",
    journal: "Communications Physics",
    url: "https://www.nature.com/commsphys.rss",
    subjects: ["physics", "open access"],
  },
  {
    publisher: "Nature",
    journal: "Scientific Data",
    url: "https://www.nature.com/sdata.rss",
    subjects: ["data", "science"],
  },
  {
    publisher: "Nature",
    journal: "npj Digital Medicine",
    url: "https://www.nature.com/npjdigitalmed.rss",
    subjects: ["medicine", "digital health"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Biophysics",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=biophysics",
    subjects: ["biophysics", "biology"],
  },
  {
    publisher: "Nature",
    journal: "npj Genomic Medicine",
    url: "https://www.nature.com/npjgenmed.rss",
    subjects: ["genomics", "medicine"],
  },
  {
    publisher: "Nature",
    journal: "npj Systems Biology and Applications",
    url: "https://www.nature.com/npjsba.rss",
    subjects: ["systems biology", "biology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "Bioengineered",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=kbie20",
    subjects: ["bioengineering", "biology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "Critical Reviews in Biotechnology",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=ibty20",
    subjects: ["biotechnology", "reviews"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "Journal of Biomolecular Structure and Dynamics",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=tbsm20",
    subjects: ["structural biology", "biology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "Journal of Enzyme Inhibition and Medicinal Chemistry",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=ienz20",
    subjects: ["medicinal chemistry", "biology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "mAbs",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=kmab20",
    subjects: ["immunology", "biotechnology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "Nanotoxicology",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=inan20",
    subjects: ["nanoscience", "toxicology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "RNA Biology",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=krnb20",
    subjects: ["rna", "biology"],
  },
  {
    publisher: "Taylor & Francis",
    journal: "Virulence",
    url: "https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=kvir20",
    subjects: ["microbiology", "infectious disease"],
  },
  {
    publisher: "Cambridge Core",
    journal: "animal",
    url: "https://www.cambridge.org/core/rss/product/id/7CC89400BC979479B6AE7BDEF995211F",
    subjects: ["animal science", "biology"],
  },
  {
    publisher: "Cambridge Core",
    journal: "Psychological Medicine",
    url: "https://www.cambridge.org/core/rss/product/id/2E4A9A64B37548F25362F3235C223463",
    subjects: ["psychiatry", "medicine"],
  },
  {
    publisher: "Cambridge Core",
    journal: "British Journal of Nutrition",
    url: "https://www.cambridge.org/core/rss/product/id/D6F69FEC7A749C38806D291D4ADA568B",
    subjects: ["nutrition", "medicine"],
  },
  {
    publisher: "Nature",
    journal: "npj Quantum Information",
    url: "https://www.nature.com/npjqi.rss",
    subjects: ["quantum", "physics"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Physics",
    url: "https://www.nature.com/natrevphys.rss",
    subjects: ["physics", "review"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Bioinformatics",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=bioinformatics",
    subjects: ["bioinformatics", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Biochemistry",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=biochemistry",
    subjects: ["biochemistry", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Immunity",
    url: "https://www.cell.com/immunity/current.rss",
    subjects: ["immunology", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Neuron",
    url: "https://www.cell.com/neuron/current.rss",
    subjects: ["neuroscience", "biology"],
  },
  {
    publisher: "ACS",
    journal: "Accounts of Chemical Research",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=achre4",
    subjects: ["chemistry", "reviews"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Bio Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aabmcb",
    subjects: ["biomaterials", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Electronic Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aaembp",
    subjects: ["electronics", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Energy Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aaemcq",
    subjects: ["energy", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Materials & Interfaces",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aamick",
    subjects: ["materials", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Nano Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aanmf6",
    subjects: ["nanoscience", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Optical Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aaoma6",
    subjects: ["optics", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Applied Polymer Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aapmcd",
    subjects: ["polymers", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Biomaterials Science & Engineering",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=abseba",
    subjects: ["biomaterials", "engineering"],
  },
  {
    publisher: "ACS",
    journal: "ACS Catalysis",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=accacs",
    subjects: ["catalysis", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Central Science",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=acscii",
    subjects: ["chemistry", "open access"],
  },
  {
    publisher: "ACS",
    journal: "ACS Chemical Biology",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=acbcct",
    subjects: ["chemical biology", "biology"],
  },
  {
    publisher: "ACS",
    journal: "ACS Chemical Neuroscience",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=acncdm",
    subjects: ["neuroscience", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Earth and Space Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aesccq",
    subjects: ["earth science", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Energy Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aelccp",
    subjects: ["energy", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Environmental Au",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aeacc4",
    subjects: ["environment", "open access"],
  },
  {
    publisher: "ACS",
    journal: "ACS ES&T Air",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aeacb3",
    subjects: ["environment", "air quality"],
  },
  {
    publisher: "ACS",
    journal: "ACS ES&T Engineering",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aeecco",
    subjects: ["environment", "engineering"],
  },
  {
    publisher: "ACS",
    journal: "ACS ES&T Water",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aewcaa",
    subjects: ["environment", "water"],
  },
  {
    publisher: "ACS",
    journal: "ACS Food Science & Technology",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=afsthl",
    subjects: ["food science", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Infectious Diseases",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aidcbc",
    subjects: ["infectious disease", "medicine"],
  },
  {
    publisher: "ACS",
    journal: "ACS Macro Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=amlccd",
    subjects: ["polymers", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Materials Au",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=amacgu",
    subjects: ["materials", "open access"],
  },
  {
    publisher: "ACS",
    journal: "ACS Materials Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=amlcef",
    subjects: ["materials", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Nano",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=ancac3",
    subjects: ["nanoscience", "materials"],
  },
  {
    publisher: "ACS",
    journal: "ACS Omega",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=acsodf",
    subjects: ["chemistry", "open access"],
  },
  {
    publisher: "ACS",
    journal: "ACS Pharmacology & Translational Science",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=aptsfn",
    subjects: ["pharmacology", "medicine"],
  },
  {
    publisher: "Cell Press",
    journal: "Chem",
    url: "https://www.cell.com/chem/current.rss",
    subjects: ["chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Photonics",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=apchd5",
    subjects: ["photonics", "materials"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Stem Cell",
    url: "https://www.cell.com/cell-stem-cell/current.rss",
    subjects: ["stem cells", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Reports",
    url: "https://www.cell.com/cell-reports/current.rss",
    subjects: ["biology", "multidisciplinary"],
  },
  {
    publisher: "Nature",
    journal: "Nature Biotechnology",
    url: "https://www.nature.com/nbt.rss",
    subjects: ["biology", "biotechnology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Methods",
    url: "https://www.nature.com/nmeth.rss",
    subjects: ["biology", "methods"],
  },
  {
    publisher: "Nature",
    journal: "Nature Medicine",
    url: "https://www.nature.com/nm.rss",
    subjects: ["medicine", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Genetics",
    url: "https://www.nature.com/ng.rss",
    subjects: ["genetics", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Neuroscience",
    url: "https://www.nature.com/neuro.rss",
    subjects: ["neuroscience", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Cell Biology",
    url: "https://www.nature.com/ncb.rss",
    subjects: ["cell biology", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Chemical Biology",
    url: "https://www.nature.com/nchembio.rss",
    subjects: ["chemical biology", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Chemistry",
    url: "https://www.nature.com/nchem.rss",
    subjects: ["chemistry"],
  },
  {
    publisher: "Nature",
    journal: "Nature Physics",
    url: "https://www.nature.com/nphys.rss",
    subjects: ["physics"],
  },
  {
    publisher: "Nature",
    journal: "Nature Materials",
    url: "https://www.nature.com/nmat.rss",
    subjects: ["materials", "physics"],
  },
  {
    publisher: "Nature",
    journal: "Nature Climate Change",
    url: "https://www.nature.com/nclimate.rss",
    subjects: ["climate", "environment"],
  },
  {
    publisher: "Nature",
    journal: "Nature Geoscience",
    url: "https://www.nature.com/ngeo.rss",
    subjects: ["earth science", "environment"],
  },
  {
    publisher: "Nature",
    journal: "Nature Communications",
    url: "https://www.nature.com/ncomms.rss",
    subjects: ["multidisciplinary", "science"],
  },
  {
    publisher: "Nature",
    journal: "Scientific Reports",
    url: "https://www.nature.com/srep.rss",
    subjects: ["multidisciplinary", "science"],
  },
  {
    publisher: "Nature",
    journal: "Nature Plants",
    url: "https://www.nature.com/nplants.rss",
    subjects: ["plant science", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Microbiology",
    url: "https://www.nature.com/nmicrobiol.rss",
    subjects: ["microbiology", "biology"],
  },
  {
    publisher: "Nature",
    journal: "Nature Immunology",
    url: "https://www.nature.com/ni.rss",
    subjects: ["immunology", "biology"],
  },
  {
    publisher: "Science/AAAS",
    journal: "Science",
    url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science",
    subjects: ["multidisciplinary", "science"],
  },
  {
    publisher: "Science/AAAS",
    journal: "Science Advances",
    url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=sciadv",
    subjects: ["multidisciplinary", "open access"],
  },
  {
    publisher: "Science/AAAS",
    journal: "Science Immunology",
    url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=sciimmunol",
    subjects: ["immunology", "biology"],
  },
  {
    publisher: "Science/AAAS",
    journal: "Science Robotics",
    url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=scirobotics",
    subjects: ["robotics", "engineering"],
  },
  {
    publisher: "Science/AAAS",
    journal: "Science Signaling",
    url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=signaling",
    subjects: ["cell biology", "biology"],
  },
  {
    publisher: "Science/AAAS",
    journal: "Science Translational Medicine",
    url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=stm",
    subjects: ["medicine", "translational research"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell",
    url: "https://www.cell.com/cell/current.rss",
    subjects: ["biology", "medicine"],
  },
  {
    publisher: "Cell Press",
    journal: "Cancer Cell",
    url: "https://www.cell.com/cancer-cell/current.rss",
    subjects: ["cancer", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Chemical Biology",
    url: "https://www.cell.com/cell-chemical-biology/current.rss",
    subjects: ["chemical biology", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Genomics",
    url: "https://www.cell.com/cell-genomics/current.rss",
    subjects: ["genomics", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Host & Microbe",
    url: "https://www.cell.com/cell-host-microbe/current.rss",
    subjects: ["microbiology", "immunology"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Metabolism",
    url: "https://www.cell.com/cell-metabolism/current.rss",
    subjects: ["metabolism", "biology"],
  },
  {
    publisher: "Cell Press",
    journal: "Cell Reports Medicine",
    url: "https://www.cell.com/cell-reports-medicine/current.rss",
    subjects: ["medicine", "biology"],
  },
  {
    publisher: "ACS",
    journal: "ACS Polymers Au",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=apaccd",
    subjects: ["polymers", "open access"],
  },
  {
    publisher: "ACS",
    journal: "ACS Sensors",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=ascefj",
    subjects: ["sensors", "engineering"],
  },
  {
    publisher: "ACS",
    journal: "ACS Sustainable Chemistry & Engineering",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=ascecg",
    subjects: ["sustainability", "chemistry"],
  },
  {
    publisher: "Wiley",
    journal: "Angewandte Chemie International Edition",
    url: "https://onlinelibrary.wiley.com/feed/15213773/most-recent",
    subjects: ["chemistry"],
  },
  {
    publisher: "Wiley",
    journal: "Advanced Science",
    url: "https://onlinelibrary.wiley.com/feed/21983844/most-recent",
    subjects: ["multidisciplinary", "open access"],
  },
  {
    publisher: "Wiley",
    journal: "Advanced Materials",
    url: "https://onlinelibrary.wiley.com/feed/15214095/most-recent",
    subjects: ["materials", "chemistry"],
  },
  {
    publisher: "Wiley",
    journal: "Chemistry - A European Journal",
    url: "https://onlinelibrary.wiley.com/feed/15213765/most-recent",
    subjects: ["chemistry"],
  },
  {
    publisher: "Wiley",
    journal: "Ecology Letters",
    url: "https://onlinelibrary.wiley.com/feed/14610248/most-recent",
    subjects: ["ecology", "environment"],
  },
  {
    publisher: "Wiley",
    journal: "EMBO Journal",
    url: "https://onlinelibrary.wiley.com/feed/14602075/most-recent",
    subjects: ["molecular biology", "biology"],
  },
  {
    publisher: "Wiley",
    journal: "Global Change Biology",
    url: "https://onlinelibrary.wiley.com/feed/13652486/most-recent",
    subjects: ["climate", "environment"],
  },
  {
    publisher: "Wiley",
    journal: "Journal of Applied Ecology",
    url: "https://onlinelibrary.wiley.com/feed/13652664/most-recent",
    subjects: ["ecology", "environment"],
  },
  {
    publisher: "Wiley",
    journal: "Methods in Ecology and Evolution",
    url: "https://onlinelibrary.wiley.com/feed/2041210X/most-recent",
    subjects: ["ecology", "methods"],
  },
  {
    publisher: "Wiley",
    journal: "Molecular Ecology",
    url: "https://onlinelibrary.wiley.com/feed/1365294X/most-recent",
    subjects: ["ecology", "genetics"],
  },
  {
    publisher: "Wiley",
    journal: "Plant Biotechnology Journal",
    url: "https://onlinelibrary.wiley.com/feed/14677652/most-recent",
    subjects: ["plant science", "biotechnology"],
  },
  {
    publisher: "Wiley",
    journal: "Small",
    url: "https://onlinelibrary.wiley.com/feed/16136829/most-recent",
    subjects: ["materials", "nanoscience"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Cell",
    url: "https://rss.sciencedirect.com/publication/science/00928674",
    subjects: ["biology", "medicine"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Current Biology",
    url: "https://rss.sciencedirect.com/publication/science/09609822",
    subjects: ["biology"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Molecular Cell",
    url: "https://rss.sciencedirect.com/publication/science/10972765",
    subjects: ["molecular biology", "biology"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "The Lancet",
    url: "https://rss.sciencedirect.com/publication/science/01406736",
    subjects: ["medicine"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Journal of Molecular Biology",
    url: "https://rss.sciencedirect.com/publication/science/00222836",
    subjects: ["molecular biology", "biology"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Biological Psychiatry",
    url: "https://rss.sciencedirect.com/publication/science/00063223",
    subjects: ["psychiatry", "neuroscience"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Water Research",
    url: "https://rss.sciencedirect.com/publication/science/00431354",
    subjects: ["environment", "water"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Environmental Science & Policy",
    url: "https://rss.sciencedirect.com/publication/science/14629011",
    subjects: ["environment", "policy"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Artificial Intelligence",
    url: "https://rss.sciencedirect.com/publication/science/00043702",
    subjects: ["computer science", "artificial intelligence"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Pattern Recognition",
    url: "https://rss.sciencedirect.com/publication/science/00313203",
    subjects: ["computer science", "artificial intelligence"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Energy",
    url: "https://rss.sciencedirect.com/publication/science/03605442",
    subjects: ["energy", "engineering"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Renewable Energy",
    url: "https://rss.sciencedirect.com/publication/science/09601481",
    subjects: ["energy", "environment"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Trends in Ecology & Evolution",
    url: "https://rss.sciencedirect.com/publication/science/01695347",
    subjects: ["ecology", "evolution"],
  },
  {
    publisher: "Elsevier/ScienceDirect",
    journal: "Trends in Genetics",
    url: "https://rss.sciencedirect.com/publication/science/01689525",
    subjects: ["genetics", "biology"],
  },
  {
    publisher: "PNAS",
    journal: "Proceedings of the National Academy of Sciences",
    url: "https://www.pnas.org/action/showFeed?type=etoc&feed=rss&jc=PNAS",
    subjects: ["multidisciplinary", "science"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Physical Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=phys-sci",
    subjects: ["physical sciences"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Physics",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=phys",
    subjects: ["physics"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Chemistry",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=chem",
    subjects: ["chemistry"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Applied Mathematics",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=app-math",
    subjects: ["applied mathematics"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Applied Physical Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=app-phys",
    subjects: ["applied physical sciences"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Astronomy",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=astro",
    subjects: ["astronomy"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Biophysics and Computational Biology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=biophys",
    subjects: ["biophysics", "computational biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Computer Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=comp-sci",
    subjects: ["computer science"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Earth, Atmospheric, and Planetary Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=earth-sci",
    subjects: ["earth science", "atmospheric science", "planetary science"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Engineering",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=eng",
    subjects: ["engineering"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Mathematics",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=math",
    subjects: ["mathematics"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Statistics",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=stat",
    subjects: ["statistics"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Biological Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=bio-sci",
    subjects: ["biological sciences"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Sustainability Science",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=sustainability",
    subjects: ["sustainability"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Agricultural Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=ag-sci",
    subjects: ["agriculture"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Applied Biological Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=app-bio",
    subjects: ["applied biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Biochemistry",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=biochem",
    subjects: ["biochemistry"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Cell Biology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=cell-bio",
    subjects: ["cell biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Developmental Biology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=dev-bio",
    subjects: ["developmental biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Ecology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=eco",
    subjects: ["ecology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Evolution",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=evolution",
    subjects: ["evolution"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Genetics",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=genetics",
    subjects: ["genetics"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Immunology and Inflammation",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=immun",
    subjects: ["immunology", "inflammation"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Medical Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=med-sci",
    subjects: ["medicine"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Microbiology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=microbio",
    subjects: ["microbiology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Neuroscience",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=neuro",
    subjects: ["neuroscience"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Pharmacology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=pharm",
    subjects: ["pharmacology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Physiology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=physio",
    subjects: ["physiology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Plant Biology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=plant-bio",
    subjects: ["plant biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Population Biology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=pop-bio",
    subjects: ["population biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Systems Biology",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=sys-bio",
    subjects: ["systems biology"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Social Science",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=soc-sci",
    subjects: ["social science"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Demography",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=demo",
    subjects: ["demography"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Economic Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=econ-sci",
    subjects: ["economics"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Political Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=pol-sci",
    subjects: ["political science"],
  },
  {
    publisher: "PNAS",
    journal: "PNAS: Psychological and Cognitive Sciences",
    url: "https://www.pnas.org/action/showFeed?type=searchTopic&feed=rss&taxonomyCode=topic&tagCode=psych",
    subjects: ["psychology", "cognitive science"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: All",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=all",
    subjects: ["preprints", "biology"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Animal Behavior and Cognition",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=animal_behavior_and_cognition",
    subjects: ["animal behavior", "cognition"],
  },
  {
    publisher: "ACS",
    journal: "The Journal of Physical Chemistry Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jpclcd",
    subjects: ["physical chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "The Journal of Physical Chemistry C",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jpccck",
    subjects: ["physical chemistry", "materials"],
  },
  {
    publisher: "ACS",
    journal: "The Journal of Physical Chemistry B",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jpcbfk",
    subjects: ["physical chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "The Journal of Physical Chemistry A",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jpcafh",
    subjects: ["physical chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "ACS Synthetic Biology",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=asbcd6",
    subjects: ["synthetic biology", "biology"],
  },
  {
    publisher: "ACS",
    journal: "Analytical Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=ancham",
    subjects: ["chemistry", "methods"],
  },
  {
    publisher: "ACS",
    journal: "Biochemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=bichaw",
    subjects: ["biochemistry", "biology"],
  },
  {
    publisher: "ACS",
    journal: "Bioconjugate Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=bcches",
    subjects: ["chemical biology", "biochemistry"],
  },
  {
    publisher: "ACS",
    journal: "Biomacromolecules",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=bomaf6",
    subjects: ["materials", "biology"],
  },
  {
    publisher: "ACS",
    journal: "Chemical Research in Toxicology",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=crtoec",
    subjects: ["toxicology", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Chemical Reviews",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=chreay",
    subjects: ["chemistry", "reviews"],
  },
  {
    publisher: "ACS",
    journal: "Chemistry of Materials",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=cmatex",
    subjects: ["materials", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Crystal Growth & Design",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=cgdefu",
    subjects: ["crystallography", "materials"],
  },
  {
    publisher: "ACS",
    journal: "Energy & Fuels",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=enfuem",
    subjects: ["energy", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Environmental Science & Technology",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=esthag",
    subjects: ["environment", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Environmental Science & Technology Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=estlcu",
    subjects: ["environment", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Industrial & Engineering Chemistry Research",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=iecred",
    subjects: ["chemical engineering", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Inorganic Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=inocaj",
    subjects: ["inorganic chemistry", "chemistry"],
  },
  {
    publisher: "bioRxiv/medRxiv",
    journal: "bioRxiv: Bioengineering",
    url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=bioengineering",
    subjects: ["bioengineering", "biology"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Agricultural and Food Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jafcau",
    subjects: ["food science", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Chemical Information and Modeling",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jcisd8",
    subjects: ["cheminformatics", "modeling"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Chemical Theory and Computation",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jctcce",
    subjects: ["computational chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Medicinal Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jmcmar",
    subjects: ["medicinal chemistry", "medicine"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Natural Products",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jnprdf",
    subjects: ["natural products", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Organic Chemistry",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=joceah",
    subjects: ["organic chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Proteome Research",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jprobs",
    subjects: ["proteomics", "biology"],
  },
  {
    publisher: "ACS",
    journal: "Journal of the American Chemical Society",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jacsat",
    subjects: ["chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Langmuir",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=langd5",
    subjects: ["chemistry", "materials"],
  },
  {
    publisher: "ACS",
    journal: "Macromolecules",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=mamobx",
    subjects: ["polymers", "materials"],
  },
  {
    publisher: "ACS",
    journal: "Molecular Pharmaceutics",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=mpohbp",
    subjects: ["pharmaceutics", "medicine"],
  },
  {
    publisher: "ACS",
    journal: "Nano Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=nalefd",
    subjects: ["nanoscience", "materials"],
  },
  {
    publisher: "ACS",
    journal: "Organic Letters",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=orlef7",
    subjects: ["organic chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Organic Process Research & Development",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=oprdfk",
    subjects: ["organic chemistry", "process chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Organometallics",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=orgnd7",
    subjects: ["organometallic chemistry", "chemistry"],
  },
  {
    publisher: "ACS",
    journal: "Journal of Chemical & Engineering Data",
    url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=jceaax",
    subjects: ["chemical engineering", "data"],
  },
  {
    publisher: "Nature",
    journal: "Nature Reviews Rheumatology",
    url: "https://www.nature.com/nrrheum.rss",
    subjects: ["medicine", "rheumatology", "review"],
  },
];
